version: "3"
services:
  app:
    container_name: pure-ftpd
    image: stilliard/pure-ftpd
    volumes:
      - ./data:/etc/pure-ftpd
    ports:
      - "21:21"
      - "30000:30000"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
      - "30004:30004"
      - "30005:30005"
      - "30006:30006"
      - "30007:30007"
      - "30008:30008"
      - "30009:30009"
    environment:
      PUBLICHOST: localhost
